// Create array "deck" containing each card object
var deck = [
  {rank: 1, unicode: "🂡"}, {rank: 1, unicode: "🂱"},
  {rank: 1, unicode: "🃁"}, {rank: 1, unicode: "🃑"},
  {rank: 2, unicode: "🂢"}, {rank: 2, unicode: "🂲"},
  {rank: 2, unicode: "🃂"}, {rank: 2, unicode: "🃒"},
  {rank: 3, unicode: "🂣"}, {rank: 3, unicode: "🂳"},
  {rank: 3, unicode: "🃃"}, {rank: 3, unicode: "🃓"},
  {rank: 4, unicode: "🂤"}, {rank: 4, unicode: "🂴"},
  {rank: 4, unicode: "🃄"}, {rank: 4, unicode: "🃔"},
  {rank: 5, unicode: "🂥"}, {rank: 5, unicode: "🂵"},
  {rank: 5, unicode: "🃅"}, {rank: 5, unicode: "🃕"},
  {rank: 6, unicode: "🂦"}, {rank: 6, unicode: "🂶"},
  {rank: 6, unicode: "🃆"}, {rank: 6, unicode: "🃖"},
  {rank: 7, unicode: "🂧"}, {rank: 7, unicode: "🂷"},
  {rank: 7, unicode: "🃇"}, {rank: 7, unicode: "🃗"},
  {rank: 8, unicode: "🂨"}, {rank: 8, unicode: "🂸"},
  {rank: 8, unicode: "🃈"}, {rank: 8, unicode: "🃘"},
  {rank: 9, unicode: "🂩"}, {rank: 9, unicode: "🂹"},
  {rank: 9, unicode: "🃉"}, {rank: 9, unicode: "🃙"},
  {rank: 10, unicode: "🂪"}, {rank: 10, unicode: "🂺"},
  {rank: 10, unicode: "🃊"}, {rank: 10, unicode: "🃚"},
  {rank: 11, unicode: "🂫"}, {rank: 11, unicode: "🂻"},
  {rank: 11, unicode: "🃋"}, {rank: 11, unicode: "🃛"},
  {rank: 12, unicode: "🂭"}, {rank: 12, unicode: "🂽"},
  {rank: 12, unicode: "🃍"}, {rank: 12, unicode: "🃝"},
  {rank: 13, unicode: "🂮"}, {rank: 13, unicode: "🂾"},
  {rank: 13, unicode: "🃎"}, {rank: 13, unicode: "🃞"}
  ];

var msgs = {
  1: 'Waterfall',
  2: 'Pick two people, and make them drink.',
  3: 'Three is me. Take 3 drinks.',
  4: 'Take 2 drinks, and give out 2.',
  5: 'Set a rule',
  6: 'Thumb rule - Place a thumb on the table, last person to do so drinks.',
  7: 'Hand to heaven, last person to do so drinks.',
  8: 'Choose a mate, every time they drink, you drink.',
  9: 'Rhyme time - Pick a word, everyone rhymes against it, if you get stumped you drink.',
  10: 'Categories, pick a category, if you get stumped..you drink.',
  11: 'Dudes drink...',
  12: 'Ladies drink...',
  13: "King. If it isn't the last king, add to kings cup. If last King, drink kings cup."
};
